### ISSUE TITLE
Can support muilti ds18b20 ?

### ISSUE THREAD

**Issue by tinamore** [lpodkalicki/attiny-ds18b20-library#1]
Hi,

Thanks for project

I have a question: Can support muilti ds18b20 (example two ds18b20) ?

Thanks

**Comment by lpodkalicki** [comment]
Hi, it has been designed to support only one onewire connection. However, It's not the first time someone is asking for that functionality. I'll update the api to support many connections.

**Comment by lpodkalicki** [comment]
Okey. I added these changes. Could you verify?

**Comment by tinamore** [comment]
Hi,
Thanks for updated
I will test, if error i will feeback.
Thank you very much
